baseURL: "https://www.bensyz.com"
title: Ben's Blog
theme: my-hugo-theme
disablePathToLower: true
publishDir: docs
languageCode: en-us

params:
  icp_record: 浙ICP备2021032097
  public_safety_record: 浙公网安备 33028102001039号
  public_safety_record_number: 33028102001039
  selected_item_list: "blogs:Blogs;tips:Tips;study_notes:Study Notes;about:About"


sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  publishDate:
    - publishDate
    - date
  lastMod:
    - lastMod
    - publishDate
    - date

markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: [asciidoctor-latex]
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: false
    smartypants: false
    smartypantsQuotesNBSP: false
    taskLists: true
  defaultMarkdownHandler: pandoc
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
